### PR TITLE
Bugfix/shapefil bounding box reversed axis

### PR DESCRIPTION
**Pull request by lmarini**

### CODE REVIEW

**Review by tcnichol — APPROVED** [review]
I'm marking this one approved. Looks good.

**Comment by lmarini** [comment]
@tcnichol do you have a file handy where this was happening that we can use to test? looking through my files as well

**Comment by max-zilla** [comment]
@lmarini @tcnichol can we merge this?

**Comment by tcnichol** [comment]
@max-zilla I would say Yes, I haven't been able to find a file that we can test (one that didn't work before but works now) but it looks good to me. It would be nice to have these in since they should fix issues with a couple of projects.

**Pull request merged**
